project:
  name: quickstart-vmware-tanzu-application-platform
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  template: templates/aws-tap-entrypoint-new-vpc.template.yaml
  parameters:
    AcceptEULAs: --override--
    AcceptCEIP: --override--
    AvailabilityZones: $[taskcat_genaz_3]
    NumberOfAZs: 3
    KeyPairName: --override--
    RemoteAccessCidr: --override--
    S3TAPConfigBucketName: $[taskcat_random-string]-$[taskcat_current_region]
    EKSClusterName: $[taskcat_random-string]
    NumberOfNodes: 4
    MaxNumberOfNodes: 4
    TanzuNetUsername: --override--
    TanzuNetPassword: --override--
    TanzuNetApiToken: --override--
    TAPDomainName: --override--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  regions:
    - us-east-1
tests:
  default:
    regions:
      - us-west-2
