#@ load("@ytt:data", "data")
---
profile: full
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: #@ data.values.repositories.build_service
  kp_default_repository_username: #@ data.values.ecr_registry.username
  kp_default_repository_password: #@ data.values.ecr_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ data.values.tanzunet.password
  pull_from_kp_default_repo: true
  enable_automatic_dependency_updates: false

supply_chain: testing

ootb_supply_chain_testing:
  registry:
    server: #@ data.values.repositories.workload.server
    repository: #@ data.values.repositories.workload.ootb_repo_prefix
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: #@ "learning-center.{}".format(data.values.dns.domain_name)

ootb_delivery_basic:
  service_account: default

tap_gui:
  ingressEnabled: true
  ingressDomain: #@ data.values.dns.domain_name
  service_type: ClusterIP # NodePort for distributions that don't support LoadBalancer
  app_config:
    supplyChain:
      enablePlugin: true
    auth:
      allowGuestAccess: true
    backend:
      baseUrl: #@ "http://tap-gui.{}".format(data.values.dns.domain_name)
      cors:
        origin: #@ "http://tap-gui.{}".format(data.values.dns.domain_name)
    app:
      baseUrl: #@ "http://tap-gui.{}".format(data.values.dns.domain_name)

metadata_store:
  app_service_type: LoadBalancer

contour:
  envoy:
    service:
      type: LoadBalancer

cnrs:
  domain_name: #@ data.values.dns.domain_name

grype:
  namespace: #@ data.values.repositories.workload.namespace
  targetImagePullSecret: registry-credentials
