#@data/values
---
tanzunet:
  server: registry.tanzu.vmware.com
  relocate_images: "Yes"
  secrets:
    credentials_arn:
cluster_essentials_bundle:
  bundle: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle
  file_hash: sha256:c7c4cb124c06ca0b6a5a6c31617781fd5b4513e03df1cb49d5d19e91c7166644
  version: 1.2.0-rc.1
tap:
  name: tap
  namespace: tap-install
  repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  version: 1.2.0
cluster:
  name: example-tap-eks-cluster
dns:
  domain_name: tap.local
  zone_id: Z0123456789ABCDEFGHIJ
repositories:
  tap_packages: 012345678901.dkr.ecr.us-east-1.amazonaws.com/621187b4-c917-46c0-9341-f5067b3afd97/tanzu-application-platform/tap-packages
  cluster_essentials: 012345678901.dkr.ecr.us-east-1.amazonaws.com/621187b4-c917-46c0-9341-f5067b3afd97/tanzu-cluster-essentials/bundle
  build_service: 012345678901.dkr.ecr.us-east-1.amazonaws.com/621187b4-c917-46c0-9341-f5067b3afd97/tap-build-service
  workload:
    name: tanzu-java-web-app-workload
    namespace: tap-workload
    repository: 012345678901.dkr.ecr.us-east-1.amazonaws.com/621187b4-c917-46c0-9341-f5067b3afd97/tap-supply-chain/tanzu-java-web-app-workload-tap-workload
    bundle_repository: 012345678901.dkr.ecr.us-east-1.amazonaws.com/621187b4-c917-46c0-9341-f5067b3afd97/tap-supply-chain/tanzu-java-web-app-workload-tap-workload-bundle
