AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template is a child template to both the aws-tap-entrypoint.newvpc and
  aws-tap-entrypoint.existingvpc templates with all parameters being passed
  from those parent templates. This template will focus on the creation of any
  shared services that are being leveraged within the scope of the TAP
  deployment such as S3, ECR and any other services that would be considered as
  PaaS services and will exist outside of the scope of the VPC where TAP is
  deployed. (qs-1t1t2pssn)
Metadata:
  SentenceCaseExclude:
    - Bootstrap
    - Net
    - Tanzu
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC network configuration
        Parameters:
          - VpcId
      - Label:
          default: VMware Tanzu Net authentication configuration
        Parameters:
          - TanzuNetID
          - TanzuNetToken
          - TanzuNetKey
      - Label:
          default: TAP private DNS domain configuration
        Parameters:
          - DomainName
      - Label:
          default: S3 config file bucket configuration
        Parameters:
          - S3BucketName
    ParameterLabels:
      VpcId:
        default: VPC ID
      TanzuNetID:
        default: ID
      TanzuNetKey:
        default: Key
      TanzuNetToken:
        default: Token
      DomainName:
        default: Domain name
      S3BucketName:
        default: Name
Parameters:
  TanzuNetID:
    Type: String
    Description: >-
      The authentication ID or email address for authenticating to
      VMware's Tanzu Net.
    NoEcho: true
  TanzuNetKey:
    Type: String
    Description: >-
      The authentication key for authenticating to VMware's Tanzu Net.
    NoEcho: true
  TanzuNetToken:
    Type: String
    Description: >-
      The authentication token required for certain TAP installation utilities
      within the Bootstrap.
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the Route53 private hosted zone.
  DomainName:
    Type: String
    Description: >-
      Domain name that can be used for access to TAP and its corresponding
      project URLs. Available within a private DNS Zone.
    MaxLength: 1024
  S3BucketName:
    Type: String
    Description: >-
      An S3 bucket where configuration files are stored in an encrypted way for
      security purposes.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      The TAP bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
Resources:
  TanzuNetSecretUser:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetUserSecret
      Description: This secret will store the Tanzu Net UserName and Password being passed in by the consumer
      SecretString: !Sub >-
        {
          "username": "${TanzuNetID}",
          "password": "${TanzuNetKey}"
        }
  TanzuNetSecretToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetToken
      Description: This secret will store the Tanzu Net API token being passed in by the consumer
      SecretString: !Ref TanzuNetToken
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
  TAPPackagesRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tanzu-application-platform/tap-packages
      EncryptionConfiguration:
        EncryptionType: AES256
  TAPClusterEssentialsBundleRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tanzu-cluster-essentials/bundle
  TAPWorkloadRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tap-supply-chain/tanzu-java-web-app-workload-tap-workload
  TAPWorkloadBundleRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tap-supply-chain/tanzu-java-web-app-workload-tap-workload-bundle
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: VMware Tanzu Application Platform hosted zone
      Name: !Ref DomainName
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref AWS::Region
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: VMware Tanzu Application Platform wildcard record
      HostedZoneId: !Ref PrivateHostedZone
      Name: !Sub '*.${DomainName}'
      ResourceRecords:
        - tanzu.vmware.com  # We'll reference the LB CNAME here
      TTL: 60
      Type: CNAME
