AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template is a child template to both the aws-tap-entrypoint.newvpc and
  aws-tap-entrypoint.existingvpc templates with all parameters being passed
  from those parent templates. This template will focus on the creation of any
  shared services that are being leveraged within the scope of the TAP
  deployment such as S3, ECR and any other services that would be considered as
  PaaS services and will exist outside of the scope of the VPC where TAP is
  deployed. (qs-1t1t2pssn)
Metadata:
  SentenceCaseExclude:
    - Bootstrap
    - Net
    - Tanzu
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC network configuration
        Parameters:
          - VpcId
      - Label:
          default: VMware Tanzu Net authentication configuration
        Parameters:
          - TanzuNetUsername
          - TanzuNetPassword
          - TanzuNetApiToken
      - Label:
          default: TAP private DNS domain configuration
        Parameters:
          - DomainName
      - Label:
          default: S3 config file bucket configuration
        Parameters:
          - S3BucketName
    ParameterLabels:
      VpcId:
        default: VPC ID
      TanzuNetUsername:
        default: Username
      TanzuNetPassword:
        default: Password
      TanzuNetApiToken:
        default: API token
      DomainName:
        default: Domain name
      S3BucketName:
        default: Name
Parameters:
  TanzuNetUsername:
    Type: String
    Description: >-
      The VMware Tanzu Net username (authentication ID or email address).
    NoEcho: true
  TanzuNetPassword:
    Type: String
    Description: The VMware Tanzu Net password (authentication key).
    NoEcho: true
  TanzuNetApiToken:
    Type: String
    Description: The VMware Tanzu Net API token.
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the Route53 private hosted zone.
  DomainName:
    Type: String
    Description: >-
      Domain name that can be used for access to TAP and its corresponding
      project URLs. Available within a private DNS Zone.
    MaxLength: 1024
  S3BucketName:
    Type: String
    Description: >-
      An S3 bucket where configuration files are stored in an encrypted way for
      security purposes.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      The TAP bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
Resources:
  TanzuNetSecretCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetCredentials
      Description: The Tanzu Net username and password
      SecretString: !Sub >-
        {
          "username": "${TanzuNetUsername}",
          "password": "${TanzuNetPassword}"
        }
  TanzuNetSecretApiToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetApiToken
      Description: The Tanzu Net API token
      SecretString: !Ref TanzuNetApiToken
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
  TAPPackagesRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tanzu-application-platform/tap-packages
      EncryptionConfiguration:
        EncryptionType: AES256
  TAPClusterEssentialsBundleRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tanzu-cluster-essentials/bundle
  TAPWorkloadRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tap-supply-chain/tanzu-java-web-app-workload-tap-workload
  TAPWorkloadBundleRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: private/tap-supply-chain/tanzu-java-web-app-workload-tap-workload-bundle
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: VMware Tanzu Application Platform hosted zone
      Name: !Ref DomainName
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref AWS::Region
Outputs:
  TanzuNetSecretCredentialsArn:
    Description: >-
      The Amazon Resource Name (ARN) of the SecretsManager entry for the
      Tanzu Net username and password.
    Value: !Ref TanzuNetSecretCredentials
    Export:
      Name: qs-1t1t2pssn:TanzuNetSecretCredentialsArn
  TanzuNetSecretApiTokenArn:
    Description: >-
      The Amazon Resource Name (ARN) of the SecretsManager entry for the
      Tanzu Net API token.
    Value: !Ref TanzuNetSecretApiToken
    Export:
      Name: qs-1t1t2pssn:TanzuNetSecretApiTokenArn
  S3BucketArn:
    Description: >-
      The Amazon Resource Name (ARN) of the TAP configuration file bucket.
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: qs-1t1t2pssn:S3BucketArn
  PrivateHostedZoneId:
    Description: >-
      The ID that Amazon Route 53 assigned to the hosted zone upon creation.
    Value: !GetAtt PrivateHostedZone.Id
    Export:
      Name: qs-1t1t2pssn:PrivateHostedZoneId
