AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a Single-AZ, multi-subnet VPC infrastructure that will include an EC2 instance for bootstrapping an install of VMware's Tanzu
  Application Platform (TAP). In addition to the EC2 instance, a single EKS cluster, ECR instance, and S3 bucket will also be deployed
  to the VPC to support the installation of the TAP software. **WARNING** This template creates AWS resources. You will be billed for the AWS
  resources used if you create a stack from this template. (qs-1t1t2psqo)
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into a new VPC
    Order: 1
  SentenceCaseExclude:
    - Bootstrap
    - Net
    - Tanzu
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - AvailabilityZones
          - NumberOfAZs
          - KeyPairName
      - Label:
          default: VPC network configuration
        Parameters:
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PublicSubnet3CIDR
      - Label:
          default: Amazon EKS configuration
        Parameters:
          - EKSClusterName
          - NodeInstanceType
          - NumberOfNodes
          - MaxNumberOfNodes
          - RemoteAccessCIDR
      - Label:
          default: VMware Tanzu Net authentication configuration
        Parameters:
          - TanzuNetID
          - TanzuNetToken
          - TanzuNetKey
      - Label:
          default: TAP config file S3 bucket configuration
        Parameters:
          - S3TAPConfigBucketName
      - Label:
          default: AWS Quick Start S3 bucket configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      KeyPairName:
        default: SSH key name
      VPCCIDR:
        default: VPC CIDR
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private subnet 3 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      S3TAPConfigBucketName:
        default: Name
      EKSClusterName:
        default: EKS cluster name
      NodeInstanceType:
        default: Instance type
      NumberOfNodes:
        default: Number of nodes
      MaxNumberOfNodes:
        default: Maximum number of nodes
      TanzuNetID:
        default: ID
      TanzuNetKey:
        default: Key
      TanzuNetToken:
        default: Token
      QSS3BucketRegion:
        default: Region
      QSS3BucketName:
        default: Name
      QSS3KeyPrefix:
        default: Key prefix
      RemoteAccessCIDR:
        default: Remote access CIDR
Parameters:
  S3TAPConfigBucketName:
    Description: TAP requires an S3 bucket to store encrypted configuration information, this bucket name will be associated with a newly created S3 bucket for that purpose.
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      The TAP bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
  #TAPDomainName:
  #  Description: Dummy domain name that can be used for access to TAP and its corresponding project URLs. Available within a private DNS Zone.
  #  Type: String
  NumberOfAZs:
    Description: Number of Availability Zones to use in the VPC. This must match the value entered for the AvailabilityZones parameter.
    Type: String
    AllowedValues: [2, 3]
    Default: 3
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. Three
      Availability Zones are used for this deployment.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1, located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2, located in Availability Zone 2.
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.64.0/19
    Description: CIDR block for private subnet 3, located in Availability Zone 3.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1, located in Availability
      Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 2, located in Availability
      Zone 2.
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.160.0/20
    Description: CIDR block for the public (DMZ) subnet 3, located in Availability
      Zone 3.
    Type: String
  KeyPairName:
    Description: The name of the SSH key that will be used to access the Bootstrap VM and cluster nodes.
    Type: AWS::EC2::KeyPair::KeyName
  EKSClusterName:
    Description: The name of the cluster that will be created to contain the TAP deployment.
    Type: String
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*
    ConstraintDescription: >-
      Minimum length of 1. Maximum length of 100. Must start with a letter or
      number.
  NumberOfNodes:
    Description: The number of nodes that will be the minimum and created for the TAP EKS cluster.
    Type: Number
    Default: 4
    MinValue: 3
    MaxValue: 450
  MaxNumberOfNodes:
    Description: The maximum number of nodes that will be available in an auto scaling scenario for the TAP EKS cluster.
    Type: Number
    Default: 6
    MinValue: 3
    MaxValue: 450
  NodeInstanceType:
    Description: AWS EC2 instance type for each of the nodes deployed within the EKS cluster for TAP.
    Type: String
    Default: m5.xlarge
  RemoteAccessCIDR:
    Description: IP Range that will be allowed to access the EKS Cluster once deployed
    Type: String
  # BootstrapEgressFromPort:
  #   Description: Start of Port range for outbound access of the Bootstrap VM (Default 0)
  #   Type: Number
  #   Default: 0
  # BootstrapEgressToPort:
  #   Description: End of Port range for outbound access of the Bootstrap VM (Default 65535)
  #   Type: Number
  #   Default: 65535
  # BootstrapEgressCIDR:
  #   Description: IP range for outbound access of the Bootstrap VM (Default is full and open to guarantee installation success)
  #   Type: String
  #   Default: 0.0.0.0/0
  TanzuNetID:
    Description: The authentication ID or email address for authenticating to VMware's Tanzu Net.
    Type: String
    NoEcho: true
  TanzuNetKey:
    Description: The authentication key for authenticating to VMware's Tanzu Net.
    Type: String
    NoEcho: true
  TanzuNetToken:
    Description: The authentication token required for certain TAP installation utilities within the Bootstrap.
    Type: String
    NoEcho: true
  #AWSCLIToken:
  #  Description: AWS token ID used when authenticating with the AWS CLI.
  #  Type: String
  #  NoEcho: true
  #AWSCLIKey:
  #  Description: AWS token key used when authenticating with the AWS CLI.
  #  Type: String
  #  NoEcho: true
  QSS3BucketName:
    Description: Name of the S3 bucket for your copy of the Quick Start assets.
      Keep the default name unless you are customizing the template.
      Changing the name updates code references to point to a new Quick
      Start location. This name can include numbers, lowercase letters,
      uppercase letters, and hyphens, but do not start or end with a hyphen (-).
      See https://aws-quickstart.github.io/option1.html.
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a
      hyphen (-).
    Default: aws-quickstart
  QSS3KeyPrefix:
    Description:
      S3 key prefix that is used to simulate a directory for your copy of the
      Quick Start assets. Keep the default prefix unless you are customizing
      the template. Changing this prefix updates code references to point to
      a new Quick Start location. This prefix can include numbers, lowercase
      letters, uppercase letters, hyphens (-), and forward slashes (/). End
      with a forward slash.
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
      and https://aws-quickstart.github.io/option1.html.
    Type: String
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-vmware-tanzu-application-platform/
  QSS3BucketRegion:
    Description: >-
      AWS Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. Keep the default Region unless you are customizing the template.
      Changing this Region updates code references to point to a new
      Quick Start location. When using your own bucket, specify the Region.
      See https://aws-quickstart.github.io/option1.html.
    Type: String
    Default: us-east-1
Conditions:
  3AZDeployment: !Equals [!Ref NumberOfAZs, 3]
  2AZDeployment: !Or
    - !Equals [!Ref NumberOfAZs, 2]
    - !Equals [!Ref NumberOfAZs, 3]
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, aws-quickstart]
Resources:
  SharedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/aws-tap-shared.yaml
        - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
          S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
      Parameters:
        S3BucketName: !Ref S3TAPConfigBucketName
        TanzuNetID: !Ref TanzuNetID
        TanzuNetKey: !Ref TanzuNetKey
        TanzuNetToken: !Ref TanzuNetToken
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn-lint: { config: { ignore_checks: [ W9901 ] } }
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
        - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
          S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
      Parameters:
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        NumberOfAZs: !Ref NumberOfAZs
        CreateNATGateways: false
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3ACIDR: !Ref PrivateSubnet3CIDR
        PrivateSubnetATag2: "kubernetes.io/role/internal-elb="
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        PublicSubnetTag2: "kubernetes.io/role/elb="
        VPCCIDR: !Ref VPCCIDR
  # EC2Stack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - VPCStack
  #     - SharedStack
  #     - EKSQSStack
  #   Properties:
  #    TemplateURL: !Sub
  #      - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/aws-tap-bootstrap.yaml
  #      - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  #        S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
  #     Parameters:
  #       VPC: !GetAtt VPCStack.Outputs.VPCID
  #       BootstrapSubnet: !GetAtt VPCStack.Outputs.PublicSubnet1ID
  #       BootstrapOS: Ubuntu
  #       BootstrapEgressFromPort: !Ref BootstrapEgressFromPort
  #       BootstrapEgressToPort: !Ref BootstrapEgressToPort
  #       BootstrapEgressCIDR: !Ref BootstrapEgressCIDR
  #       BootstrapKeyName: !Ref KeyPairName
  #       TanzuNetID: !Ref TanzuNetID
  #       TanzuNetKey: !Ref TanzuNetKey
  #       TanzuNetToken: !Ref TanzuNetToken
  #       AWSCLIToken: !Ref AWSCLIToken
  #       AWSCLIKey: !Ref AWSCLIKey
  EKSQSStack:
    Type: AWS::CloudFormation::Stack
    Metadata:
      cfn-lint: { config: { ignore_checks: [ W9901, E9902 ] } }
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-existing-vpc.template.yaml
        - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
          S3Region: !If [UsingDefaultBucket, !Ref AWS::Region, !Ref QSS3BucketRegion]
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !If
          - 2AZDeployment
          - !GetAtt VPCStack.Outputs.PrivateSubnet2AID
          - !Ref AWS::NoValue
        PrivateSubnet3ID: !If
          - 3AZDeployment
          - !GetAtt VPCStack.Outputs.PrivateSubnet3AID
          - !Ref AWS::NoValue
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !If
          - 2AZDeployment
          - !GetAtt VPCStack.Outputs.PublicSubnet2ID
          - !Ref AWS::NoValue
        PublicSubnet3ID: !If
          - 3AZDeployment
          - !GetAtt VPCStack.Outputs.PublicSubnet3ID
          - !Ref AWS::NoValue
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        EKSPublicAccessEndpoint: Enabled
        KeyPairName: !Ref KeyPairName
        NumberOfNodes: !Ref NumberOfNodes
        MaxNumberOfNodes: !Ref MaxNumberOfNodes
        NodeInstanceType: !Ref NodeInstanceType
        NodeInstanceFamily: Standard
        NodeGroupType: Managed
        NodeGroupOS: Amazon Linux 2
        EKSClusterName: !Ref EKSClusterName
        ClusterAutoScaler: Enabled
        ProvisionBastionHost: Disabled
        SnykIntegration: Disabled
        NewRelicIntegration: Disabled
        CalicoIntegration: Disabled
        RafaySysIntegration: Disabled
        GrafanaIntegration: Disabled
        PrometheusIntegration: Disabled
        VaultIntegration: Disabled
        ConsulIntegration: Disabled
        RancherIntegration: Disabled
        MonitoringStack: None
        ALBIngressController: Enabled
        EfsStorageClass: Disabled
