AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template is a child template to both the aws-tap-entrypoint.newvpc and
  aws-tap-entrypoint.existingvpc templates with all parameters being passed
  from those parent templates. This template will focus on the creation of any
  shared services that are being leveraged within the scope of the TAP
  deployment such as S3, ECR and any other services that would be considered as
  PaaS services and will exist outside of the scope of the VPC where TAP is
  deployed. (qs-1t1t2pssn)
Metadata:
  SentenceCaseExclude:
    - Bootstrap
    - Net
    - Tanzu
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VMware Tanzu Net authentication configuration
        Parameters:
          - TanzuNetID
          - TanzuNetToken
          - TanzuNetKey
      - Label:
          default: S3 config file bucket configuration
        Parameters:
          - S3BucketName
    ParameterLabels:
      TanzuNetID:
        default: ID
      TanzuNetKey:
        default: Key
      TanzuNetToken:
        default: Token
      S3BucketName:
        default: Name
Parameters:
  TanzuNetID:
    Type: String
    Description: >-
      The authentication ID or email address for authenticating to
      VMware's Tanzu Net.
    NoEcho: true
  TanzuNetKey:
    Type: String
    Description: >-
      The authentication key for authenticating to VMware's Tanzu Net.
    NoEcho: true
  TanzuNetToken:
    Type: String
    Description: >-
      The authentication token required for certain TAP installation utilities
      within the Bootstrap.
    NoEcho: true
  S3BucketName:
    Type: String
    Description: >-
      An S3 bucket where configuration files are stored in an encrypted way for
      security purposes.
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription:
      The TAP bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
Resources:
  TanzuNetSecretUser:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetUserSecret
      Description: This secret will store the Tanzu Net UserName and Password being passed in by the consumer
      SecretString: !Sub >-
        {
          "username": "${TanzuNetID}",
          "password": "${TanzuNetKey}"
        }
  TanzuNetSecretToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: TanzuNetToken
      Description: This secret will store the Tanzu Net API token being passed in by the consumer
      SecretString: !Ref TanzuNetToken
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
  TAPImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: tap/tap_ecr_registry
      EncryptionConfiguration:
        EncryptionType: AES256
  TAPWorkloadRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: tap/container_workload_ecr_registry
  TAPTBSRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: tap/container_tbs_ecr_registry
